"""
Ingestion pipeline v4.
Reads MARKDOWN for both sources:
  - data/gouv_md/ (scraped by scrape_service_public.py)
  - data/novatech_md/ (generated by generate_corpus.py)
Chunking by ## headers → 1 chunk = 1 section.

Usage: python data/ingest.py
"""

import os, re, hashlib, sys
from pathlib import Path
import chromadb
from chromadb.utils import embedding_functions

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.config import (
    EMBEDDING_MODEL, CHROMA_PERSIST_DIR, CHROMA_COLLECTION_NAME,
    CHUNK_SIZE, CHUNK_OVERLAP, GOUV_MD_DIR, NOVATECH_MD_DIR
)



def read_markdown(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read().strip()
    
def clean_chunk(text: str) -> str:
    """Remove noise from chunks."""
    # Remove service-public metadata lines
    text = re.sub(r"\*Sources?\s*:.*?\*", "", text)
    text = re.sub(r"\*Vérifié le.*?\*", "", text)
    text = re.sub(r"Vérifié le.*?Premier ministre\)", "", text)
    # Remove empty separators
    text = re.sub(r"^---\s*$", "", text, flags=re.MULTILINE)
    # Remove repeated blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

# ============================================================
# CHUNKING — same logic for both sources
# ============================================================
def chunk_markdown(text: str) -> list[dict]:
    """
    Split sur ## headers. 1 chunk = 1 section.
    Chaque chunk est préfixé avec le titre du document (#).
    Si une section est trop longue, re-split sur ### puis par taille.
    """
    doc_title = ""
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if m:
        doc_title = m.group(1).strip()

    sections = re.split(r"(?=^##\s+)", text, flags=re.MULTILINE)
    chunks = []

    for section in sections:
        section = section.strip()
        if len(section) < 50:
            continue

        section_title = ""
        sm = re.match(r"^##\s+(.+)$", section, re.MULTILINE)
        if sm:
            section_title = sm.group(1).strip()

        if len(section) > CHUNK_SIZE * 2:
            subs = re.split(r"(?=^###\s+)", section, flags=re.MULTILINE)
            for sub in subs:
                sub = sub.strip()
                if len(sub) < 50:
                    continue
                if len(sub) > CHUNK_SIZE * 2:
                    for sc in chunk_by_size(sub):
                        chunks.append({"text": sc, "section": section_title})
                else:
                    chunks.append({"text": sub, "section": section_title})
        else:
            chunks.append({"text": section, "section": section_title})

    # Préfixer avec le titre du document (tous les chunks ## sauf le premier qui contient déjà le # titre)
    for c in chunks:
        c["text"] = clean_chunk(c["text"])

        if doc_title and doc_title not in c["text"]:
            c["text"] = f"[{doc_title}]\n\n{c['text']}"
    chunks = [c for c in chunks if len(c["text"]) > 80]
    if len(chunks) <= 1 and len(text) > CHUNK_SIZE:
        return [{"text": t, "section": ""} for t in chunk_by_size(text)]

    return chunks


def chunk_by_size(text: str) -> list[str]:
    chunks, current = [], ""
    for s in re.split(r"(?<=[.!?])\s+", text):
        if len(current) + len(s) > CHUNK_SIZE and current:
            chunks.append(current.strip())
            current = current[-CHUNK_OVERLAP:] + " " + s if len(current) > CHUNK_OVERLAP else s
        else:
            current += " " + s
    if current.strip():
        chunks.append(current.strip())
    return chunks


# ============================================================
# LOAD ALL MARKDOWN
# ============================================================
def load_all_documents() -> list[dict]:
    documents = []

    for md_dir, source_type in [(GOUV_MD_DIR, "gouv"), (NOVATECH_MD_DIR, "novatech")]:
        if not md_dir.exists():
            print(f"  ⚠ {md_dir} non trouvé")
            continue

        files = sorted(md_dir.glob("*.md"))
        print(f"\n  [{source_type.upper()}] {len(files)} Markdown dans {md_dir}/")

        for md_path in files:
            print(f"    → {md_path.name}", end="")
            text = read_markdown(str(md_path))
            if not text:
                print(" ⚠ vide")
                continue

            chunks = chunk_markdown(text)
            print(f" → {len(chunks)} chunks")

            for i, c in enumerate(chunks):
                documents.append({
                    "text": c["text"],
                    "metadata": {
                        "source": source_type,
                        "document": md_path.stem,
                        "filename": md_path.name,
                        "section": c["section"],
                        "chunk_index": i,
                        "total_chunks": len(chunks),
                    }
                })

    return documents


# ============================================================
# INDEX
# ============================================================
def index_documents(documents: list[dict]) -> None:
    print(f"\n  Embedding : {EMBEDDING_MODEL}")
    print(f"  Collection : {CHROMA_COLLECTION_NAME}")

    ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name=EMBEDDING_MODEL) # type: ignore
    client = chromadb.PersistentClient(path=CHROMA_PERSIST_DIR) # type: ignore

    try:
        client.delete_collection(name=CHROMA_COLLECTION_NAME) # type: ignore
        print("  Collection supprimée")
    except: pass

    collection = client.create_collection(
        name=CHROMA_COLLECTION_NAME, embedding_function=ef, # type: ignore
        metadata={"hnsw:space": "cosine"}
    )

    ids, texts, metas = [], [], []
    for doc in documents:
        did = hashlib.md5(
            f"{doc['metadata']['document']}_{doc['metadata']['chunk_index']}_{doc['text'][:100]}".encode()
        ).hexdigest()
        ids.append(did)
        texts.append(doc["text"])
        metas.append(doc["metadata"])

    for i in range(0, len(ids), 500):
        end = min(i+500, len(ids))
        collection.add(ids=ids[i:end], documents=texts[i:end], metadatas=metas[i:end])
        print(f"  Indexé {end}/{len(ids)}")

    gouv = sum(1 for m in metas if m["source"] == "gouv")
    nova = sum(1 for m in metas if m["source"] == "novatech")
    print(f"\n  ✓ {len(ids)} chunks (gouv: {gouv}, novatech: {nova})")

    print(f"\n  Détail :")
    for m in metas:
        if m["chunk_index"] == 0:
            print(f"    [{m['source']}] {m['document']} — {m['total_chunks']} chunks")


def main():
    print(f"\n{'='*50}")
    print(f"  HR Assistant — Ingestion v4")
    print(f"  Sources : gouv_md/ + novatech_md/")
    print(f"  Chunking : ## Markdown headers")
    print(f"{'='*50}")

    documents = load_all_documents()
    if not documents:
        print("\n  ✗ Aucun document")
        return

    print(f"\n  Total : {len(documents)} chunks")
    index_documents(documents)
    print(f"\n  ✓ Done!\n")


if __name__ == "__main__":
    main()